import { set } from "date-fns";
import { ShiftType } from "../FrankBigCalendar";

const today = new Date();

const shiftData_provider01: ShiftType = {
    startTime: set(today, { hours: 9, minutes: 0, seconds: 0, milliseconds: 0 }),
    endTime: set(today, { hours: 18, minutes: 0, seconds: 0, milliseconds: 0 }),
    photo: 'https://www.srjca.com/wp-content/uploads/2020/09/doctor.png',
    providerUserId: '01',
    providerName: 'Thomas',
    backgroundColor: '#C530C5',
    location: {
        id: 'locationId01',
        country: 'Canada',
        province: 'Ontario',
        city: 'Toronto',
        address: '123 Main St',
        label: 'Location 1',
        unit: 'A',
        room: 'Exam Room 1',
        notes: 'Notes for Location'
    },
    bookings: [
        {
            id: '01',
            startTime: set(today, { hours: 10, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 11, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '01',
            clientName: 'John',
            location: 'locationId01',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 20,
            status: 'COMPLETE',
            serviceType: 'General Visit'
        },
        {
            id: '02',
            startTime: set(today, { hours: 11, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 12, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '02',
            clientName: 'Peter',
            location: 'locationId01',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 20,
            status: 'ARRIVED',
            serviceType: 'General Visit'            
        },
        {
            id: '03',
            startTime: set(today, { hours: 12, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 13, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '02',
            clientName: 'Juliana',
            location: 'locationId01',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 20,
            status: 'PENDING',
            serviceType: 'General Visit',
        },
        {
            id: '04',
            startTime: set(today, { hours: 13, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 14, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '03',
            clientName: 'Eric',
            location: 'locationId01',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 20,
            status: 'MISS',
            serviceType: 'General Visit'
        },
        {
            id: '05',
            startTime: set(today, { hours: 15, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 16, minutes: 0, seconds: 0, milliseconds: 0 }),
            location: 'locationId01',
            bookingMethod: ['ONLINE'],
            status: 'AVAILABLE',
        },
        {
            id: '06',
            startTime: set(today, { hours: 16, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 17, minutes: 0, seconds: 0, milliseconds: 0 }),
            bookingMethod: ['ONLINE', 'PHONE'],
            location: 'locationId01',
            status: 'AVAILABLE',
        },
    ]
}

const shiftData_provider02_01: ShiftType = {
    startTime: set(today, { hours: 10, minutes: 0, seconds: 0, milliseconds: 0 }),
    endTime: set(today, { hours: 13, minutes: 0, seconds: 0, milliseconds: 0 }),
    photo: 'https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg?crop=0.66698xw:1xh;center,top&resize=640:*',
    providerUserId: '02',
    providerName: 'Kale',
    backgroundColor: '#0071E9',
    bookings: [
        {
            id: '07',
            startTime: set(today, { hours: 10, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 10, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '04',
            clientName: 'Ethan',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 23,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '08',
            startTime: set(today, { hours: 10, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 11, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '05',
            clientName: 'Jason',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 25,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '09',
            startTime: set(today, { hours: 11, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 12, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '06',
            clientName: 'Joey',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 35,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '10',
            startTime: set(today, { hours: 12, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 13, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '06',
            clientName: 'Zoey',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 40,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
    ]
}

const shiftData_provider02_02: ShiftType = {
    startTime: set(today, { hours: 15, minutes: 0, seconds: 0, milliseconds: 0 }),
    endTime: set(today, { hours: 20, minutes: 0, seconds: 0, milliseconds: 0 }),
    photo: 'https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg?crop=0.66698xw:1xh;center,top&resize=640:*',
    providerUserId: '02',
    providerName: 'Kale',
    backgroundColor: '#0071E9',
    bookings: [
        {
            id: '15',
            startTime: set(today, { hours: 15, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 15, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '07',
            clientName: 'Bob',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 20,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '16',
            startTime: set(today, { hours: 15, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 16, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '08',
            clientName: 'Kevin',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 23,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '17',
            startTime: set(today, { hours: 16, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 16, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '09',
            clientName: 'Christin',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 18,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '18',
            startTime: set(today, { hours: 16, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 17, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '10',
            clientName: 'Laura',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 21,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '19',
            startTime: set(today, { hours: 17, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 17, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '11',
            clientName: 'Megan',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 22,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '20',
            startTime: set(today, { hours: 17, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 18, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '12',
            clientName: 'Alice',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 23,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '21',
            startTime: set(today, { hours: 18, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 18, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '12',
            clientName: 'Kuber',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 23,
            status: 'BOOKED',
            serviceType: 'General Visit',
        },
        {
            id: '22',
            startTime: set(today, { hours: 18, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 19, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '13',
            clientName: 'Anna',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 27,
            status: 'BOOKED',
            serviceType: 'General Visit',
          },
          {
            id: '23',
            startTime: set(today, { hours: 19, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 19, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '14',
            clientName: 'Leo',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 31,
            status: 'BOOKED',
            serviceType: 'General Visit',
          },
          {
            id: '24',
            startTime: set(today, { hours: 19, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 20, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '15',
            clientName: 'Sophia',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 22,
            status: 'BOOKED',
            serviceType: 'General Visit',
          },
    ]
}

const shiftData_provider03_01: ShiftType = {
    startTime: set(today, { hours: 7, minutes: 0, seconds: 0, milliseconds: 0 }),
    endTime: set(today, { hours: 9, minutes: 0, seconds: 0, milliseconds: 0 }),
    photo: 'https://images.theconversation.com/files/304957/original/file-20191203-66986-im7o5.jpg?ixlib=rb-4.1.0&q=45&auto=format&w=1356&h=668&fit=crop',
    providerUserId: '03',
    providerName: 'Lily',
    backgroundColor: '#E5A500',
    bookings: [
        {
            id: '11',
            startTime: set(today, { hours: 7, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 7, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '20',
            clientName: 'Lucas',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 20,
            status: 'BOOKED',
            serviceType: 'General Visit',
          },
          {
            id: '12',
            startTime: set(today, { hours: 7, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 8, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '21',
            clientName: 'Emma',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 21,
            status: 'BOOKED',
            serviceType: 'General Visit',
          },
          {
            id: '13',
            startTime: set(today, { hours: 8, minutes: 0, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 8, minutes: 30, seconds: 0, milliseconds: 0 }),
            clientUserId: '22',
            clientName: 'Noah',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Male',
            clientAge: 22,
            status: 'BOOKED',
            serviceType: 'General Visit',
          },
          {
            id: '14',
            startTime: set(today, { hours: 8, minutes: 30, seconds: 0, milliseconds: 0 }),
            endTime: set(today, { hours: 9, minutes: 0, seconds: 0, milliseconds: 0 }),
            clientUserId: '23',
            clientName: 'Olivia',
            location: 'locationId02',
            bookingMethod: ['ONLINE'],
            clientGender: 'Female',
            clientAge: 23,
            status: 'BOOKED',
            serviceType: 'General Visit',
          }
    ]
}

const shiftData_provider03_02: ShiftType = {
    startTime: set(today, { hours: 12, minutes: 15, seconds: 0, milliseconds: 0 }),
    endTime: set(today, { hours: 15, minutes: 15, seconds: 0, milliseconds: 0 }),
    photo: 'https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg?crop=0.66698xw:1xh;center,top&resize=640:*',
    providerUserId: '03',
    providerName: 'Lily',
    backgroundColor: '#E5A500',
    bookings: []
}

const shiftData_provider03_03: ShiftType = {
    startTime: set(today, { hours: 16, minutes: 30, seconds: 0, milliseconds: 0 }),
    endTime: set(today, { hours: 21, minutes: 30, seconds: 0, milliseconds: 0 }),
    photo: 'https://hips.hearstapps.com/hmg-prod/images/portrait-of-a-happy-young-doctor-in-his-clinic-royalty-free-image-1661432441.jpg?crop=0.66698xw:1xh;center,top&resize=640:*',
    providerUserId: '03',
    providerName: 'Lily',
    backgroundColor: '#E5A500',
    bookings: []
}

const shiftDataAll: ShiftType[] = [
    shiftData_provider01,
    shiftData_provider02_01,
    shiftData_provider02_02,
    shiftData_provider03_01,
    shiftData_provider03_02,
    shiftData_provider03_03
]

export const calendarSampleData = {
    shiftData_provider01, // with booking slots
    shiftData_provider02_01, // No booking slots
    shiftDataAll,
}